version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: php:8.3.10-apache
    container_name: laravel_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    # working_dir: /var/www 
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: laravel_db
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306" 
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_PORT: 3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
